### PR TITLE
x64 build

### PR DESCRIPTION
**Pull request by chcg**
- merged with https://github.com/npp-plugins/plugintemplate/releases/tag/v3.1, removed outdated files
- added x64 compile target
- dropped ansi builds
- avoid compiler warnings
- corrected VS2013 code analysis issues

, build see https://ci.appveyor.com/project/chcg/securepad containing artifacts for the release builds
, needs registration at appveyor and creation of a security token, see see https://www.appveyor.com/docs/deployment/github/#provider-settings
to use appveyor builds for github releases on tagging, see e.g. https://github.com/pnedev/compare-plugin/releases/tag/v2.0.0

### CODE REVIEW

**Comment by dominictobias** [comment]
Great stuff thanks 👏

**Comment by chcg** [comment]
@DominicTobias 

What about resource info:

            VALUE "CompanyName", "DreamInPixels, dreaminpixels.net"
            VALUE "FileDescription", "SecurePad can be used to securely encrypt plaintext documents with a key of your choice"
            VALUE "FileVersion", "2.1.0.0"
            VALUE "InternalName", "SecurePad.dll"
            VALUE "LegalCopyright", "Copyright (c) 2011 dreaminpixels.net"
            VALUE "OriginalFilename", "SecurePad.dll"
            VALUE "ProductName", "SecurePad"
            VALUE "ProductVersion", "2.1.0.0"

seems http://www.dreaminpixels.net/ is no longer correct, version should be at least 2.2 I think.

Maybe you wan't to release a version 2.3? With appveyor config or manually? PluginManager needs a zip file not just a plain dll.

**Comment by dominictobias** [comment]
Ah yeah that should really be more generic, no company name is needed and
copyright notice to MIT or something. And you're right - releasing a new
version sounds like a good idea, not sure what appveyor is will look it up
tomorrow 😜

**Comment by dominictobias** [comment]
And you're more than welcome to release it yourself as I might slow getting
round to it! I'll check the about content too maybe that could do with
updating

**Comment by chcg** [comment]
ok, Appveyor is a build service at the internet which could cooperate with github. N++ is also using it.

Release doesn't hurry. Have a look and then we could do that step.

Good night.

**Pull request merged**
